homepage:
    path:     /
    defaults: { _controller: ManageCompanyBundle:Page:index }
    methods:  GET

register:
    path:     /registro
    defaults: { _controller: ManageCompanyBundle:Restaurante:register }