<?php

namespace AppBundle\Repository;

/**
 * DomicilioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Obtengo los estados de pedido para mostrar a empleado ("Enviado", "Entregado", "Cancelado")
     *
     * @return mixed
     */
    public function getStatesOrdersByEmployee(){
        $stmt = $this->getEntityManager()->getConnection()
            ->prepare("SELECT e.id, e.estado FROM estado e WHERE e.id = 3 OR e.id = 4 OR e.id = 5 OR e.id = 6");
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
