<?php

namespace AppBundle\Repository;

/**
 * PedidoProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
