<?php

namespace AppBundle\Repository;

/**
 * PedidoPlatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoPlatoRepository extends \Doctrine\ORM\EntityRepository
{
}
