<?php

namespace AppBundle\Repository;

/**
 * PlatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatoRepository extends \Doctrine\ORM\EntityRepository
{
}
