<?php

namespace AppBundle\Repository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Devuelve un producto segÃºn su identificador
     *
     * @param $id
     * @return mixed
     */
    public function getProducto($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p.id, p.nombre, p.descripcion, p.precio FROM AppBundle:Producto p WHERE p.id = :id'
            );
        $query->setParameter('id',$id);
        $producto = $query->getResult();
        return $producto;
    }
}
