<?php

namespace AppBundle\Repository;

/**
 * RestauranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestauranteRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Muestra los campos de las tablas usuario y restaurante correspondientes a los restaurantes
     *
     * @param $idRestaurante
     * @return mixed
     */
    public function showRestaurantes()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT u.name, r FROM AppBundle:Restaurante r, AppBundle:Usuario u
            	WHERE r.id = u.idRestaurante'
            );
        $restaurantes = $query->getResult();
        return $restaurantes;
    }

    /**
     * Obtengo el restaurante con el id pasado (Datos de ambas tablas: Usuario y Restaurante)
     *
     * @param $idRestaurante
     * @return mixed
     */
    public function getInfoRestauranteLogConfigAccount($idRestaurante){
        $stmt = $this->getEntityManager()->getConnection()
                ->prepare("SELECT u.id as usuario_id, r.id as restaurante_id, u.username, u.email, r.name, r.cif, r.direccion,
                r.idLocalidad as localidad_id, l.nombre as localidad, r.idProvincia as provincia_id, r.precio_envio,r.telefono
                FROM usuario u LEFT JOIN restaurante r ON r.idUsuario = u.id LEFT JOIN localidad l ON l.id = r.idLocalidad
                WHERE r.idUsuario = :idRestaurante");
        $params = array("idRestaurante" => $idRestaurante);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }
}
