<?php
// src/AppBundle/Repository/RestauranteRepository.php
namespace AppBundle\Repository;

/**
 * RestauranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestauranteRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * Devuelve todos los restaurantes de una misma zona.
     *
     * @return mixed
     */
    public function showRestaurantes($codigo_postal)
    {
        $codigo_postal = substr($codigo_postal, 0, 3);
        $query = $this->getEntityManager()
            ->createQuery(
                "SELECT r FROM AppBundle:Restaurante r, AppBundle:Localidad l WHERE r.localidad = l.id AND l.codigoPostal LIKE '$codigo_postal%'"
            );
        $restaurantes = $query->getResult();
        return $restaurantes;
    }

    public function showProductos($idRestaurante)
    {
        $query = $this->getEntityManager()->getConnection()
            ->prepare(
                "SELECT p.id, p.nombre, p.descripcion, p.precio, tp.nombre AS tipoProducto FROM producto p 
                LEFT JOIN producto_tipo_producto ON p.id = producto_tipo_producto.idProducto
                LEFT JOIN tipo_producto tp ON producto_tipo_producto.idTipoProducto = tp.id
                WHERE p.idRestaurante = :idRestaurante AND p.disponible = '1' ORDER BY p.nombre ASC"
            );
        $query->bindParam('idRestaurante', $idRestaurante);
        $query->execute();
        return $query->fetchAll();
    }
}
