<?php

namespace AppBundle\Repository;

/**
 * TipoProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
