app:
    resource: "@AppBundle/Controller/"
    type:     annotation

manage:
    resource: "@ManageCompanyBundle/Controller/"
    prefix:   /gestion
    type:     annotation

register:
    resource: "@RegisterBundle/Controller/"
    prefix:   /registro
    type:     annotation
#    methods:  [POST, PUT, GET]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
