register:
    resource: "@RegisterBundle/Controller/"
    prefix:   /register
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

manage:
    resource: "@ManageCompanyBundle/Controller/"
    prefix:   /gestion
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
