
manage:
    resource: "@ManageCompanyBundle/Controller/"
    prefix:   /gestion
    host:     clickandeat.restaurante.local
    type:     annotation


register_restaurante:
    resource: "@RegisterBundle/Controller"
    prefix:   /restaurante
    host:     clickandeat.restaurante.local
    type:     annotation


client:
    resource: "@ClientBundle/Controller/"
    prefix:   /
    host:     clickandeat.cliente.local
    type:     annotation

employee:
    resource: "@EmployeeBundle/Controller/"
    type:     annotation
    host:     clickandeat.restaurante.local
    prefix:   /empleados

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_login:
    path:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

admin_check:
    path:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

admin_logout:
    path:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }


client_login:
    path:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

client_check:
    path:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

client_logout:
    path:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }