app:
    resource: "@AppBundle/Controller/"
    type:     annotation

manage:
    resource: "@ManageCompanyBundle/Controller/"
    type: annotation
    prefix: /gestion

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
