employee:
    resource: "@EmployeeBundle/Controller/"
    type:     annotation
    prefix:   /empleados

client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    host:     clickandeat.cliente.local
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

manage:
    resource: "@ManageCompanyBundle/Controller/"
    prefix:   /gestion
    host:     clickandeat.restaurante.local
    type:     annotation


register:
    resource: "@RegisterBundle/Controller"
    prefix:   /register
    host:     clickandeat.restaurante.local
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_login:
    path:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

admin_check:
    path:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

admin_logout:
    path:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }