# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        #AppBundle\Entity\User:
        #    algorithm: bcrypt

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER, ROLE_EDITOR, ROLE_GESTOR
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

        db_provider:
            entity:
                class: AppBundle:Restaurante
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
              pattern: ^/
              form_login:
                  provider: fos_userbundle
                  login_path: fos_user_security_login
                  check_path: fos_user_security_check
              logout: true
              anonymous: true
              switch_user: true
        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registrar, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/registro, role: ROLE_ADMIN }
        - { path: ^/gestion, role: ROLE_ADMIN }
        - { path: ^/gestion, role: ROLE_USER }
        - { path: ^/gestion, role: ROLE_EDITOR }
