# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    #encoders:
    #    AppBundle\Entity\Restaurante:
    #        algorithm: bcrypt

    #role_hierarchy:
    #    ROLE_ADMIN:       ROLE_USER, ROLE_EDITOR
    #    ROLE_SUPER_ADMIN: ROLE_ADMIN

    #access_control:
    #    - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #    - { path: ^/registro, roles: ROLE_USER }
    #    - { path: ^/*, roles: ROLE_USER }
    
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        #our_db_provider:
        #    entity: 
        #        class: AppBundle:Restaurante
        #        property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:  ^/
            #provider: our_db_provider
            anonymous: ~
            #form_login:
            #    login_path: /login
            #    check_path: /login_check
            #    always_use_default_target_path: false
            #    default_target_path:            /
            #    target_path_parameter:          _target_path
            #    use_referer:                    false
            #logout:
            #    path:   /logout
            #    target: /
            # activate different ways to authenticate

            #http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
