<?php

namespace AppBundle\Repository;

/**
 * RecorridoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecorridoRepository extends \Doctrine\ORM\EntityRepository
{
}
