<?php

namespace AppBundle\Repository;

/**
 * TipoComidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoComidaRepository extends \Doctrine\ORM\EntityRepository
{
}
